version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - RUN_ADDRESS=${RUN_ADDRESS}
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - RELEASE_MODE=${RELEASE_MODE}
      - CHAT_ID=${CHAT_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: diplomMaxbonus
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"