# Dockerfile-go
# Используем официальный базовый образ Go
FROM golang:1.20
# Устанавливаем рабочую директорию
WORKDIR /app
# Копируем go.mod и go.sum в рабочую директорию
COPY go.mod go.sum ./
# Загружаем зависимости
RUN go mod download
# Копируем исходный код в рабочую директорию
COPY . .
# Собираем приложение
RUN go build -o main .
# Запускаем приложение
CMD ["./main"]