# Берем официальный образ Node.js
FROM node:16

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и yarn.lock (если есть) в рабочую директорию
COPY client/package.json ./
COPY client/package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код в рабочую директорию
COPY client/ ./

# Собираем приложение
RUN npm build

# Устанавливаем serve глобально
RUN npm global add serve

# Запускаем приложение
CMD ["serve", "-s", "build"]